/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'doshi' at '12/24/14 5:43 PM' with Gradle 2.1
 *
 * @author doshi, @date 12/24/14 5:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
